openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing user tasks with JWT-based authentication
servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /api/{user_id}/tasks:
    get:
      summary: List all tasks for a user
      description: Retrieve all tasks belonging to the authenticated user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The user's ID (must match JWT)
          schema:
            type: string
      responses:
        '200':
          description: List of user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      security:
        - jwt_auth: []
    post:
      summary: Create a new task
      description: Create a new task for the authenticated user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The user's ID (must match JWT)
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      security:
        - jwt_auth: []

  /api/{user_id}/tasks/{id}:
    get:
      summary: Get task details
      description: Retrieve details of a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The user's ID (must match JWT)
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The task ID
          schema:
            type: string
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - jwt_auth: []
    put:
      summary: Update a task
      description: Update details of a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The user's ID (must match JWT)
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The task ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - jwt_auth: []
    delete:
      summary: Delete a task
      description: Delete a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The user's ID (must match JWT)
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The task ID
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - jwt_auth: []

  /api/{user_id}/tasks/{id}/complete:
    patch:
      summary: Toggle task completion
      description: Toggle the completion status of a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The user's ID (must match JWT)
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The task ID
          schema:
            type: string
      responses:
        '200':
          description: Task completion toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - jwt_auth: []

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the task
        user_id:
          type: string
          description: ID of the user who owns the task
        title:
          type: string
          maxLength: 255
          description: Task title
        is_completed:
          type: boolean
          description: Whether the task is completed
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Task last update timestamp
      required:
        - id
        - user_id
        - title
        - is_completed
        - created_at
        - updated_at

    CreateTaskRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
          description: Task title
      required:
        - title

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
          description: Updated task title
        is_completed:
          type: boolean
          description: Updated completion status

  responses:
    Unauthorized:
      description: Unauthorized - Invalid or missing JWT token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden - User does not have permission to access this resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not Found - Resource does not exist
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad Request - Invalid request parameters or body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code

  securitySchemes:
    jwt_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from Better Auth